### ISSUE TITLE
Java SDK: getQuery overload that enables RPC call does not make jobId available to caller

### ISSUE THREAD

**Issue by jeff303** [googleapis/java-bigquery#1592]
**Is your feature request related to a problem? Please describe.**
When using the `com.google.cloud.bigquery.BigQueryImpl#query(com.google.cloud.bigquery.QueryJobConfiguration, com.google.cloud.bigquery.BigQuery.JobOption...)` overload, the randomly generated `jobId` is not available to the caller.  This means that, in practice, the caller can't cancel this job without using reflection.

The version of `query` that accepts the `jobId` parameter (meaning, the caller can supply it) can't use the RPC/fast path.

**Describe the solution you'd like**
Either the `query` overload accepting the jobId should allow the RPC/fast path, or else the generated jobId should be made available somehow to the caller via the `TableResult` (perhaps a `.getJobReference` method).

**Describe alternatives you've considered**
Using reflection to access private methods or fields that would be necessary to implement cancellation behavior on the caller side.

**Additional context**
We would like to be able to both cancel queries (to save user cost/resources) **and** use the fast RPC path.

**Comment by stephaniewang526** [comment]
Hi, thank you for the feedback. We definitely do not plan on exposing jobId to the user since not all query operations are jobs -- only long running ones will have a jobId/jobReference generated. We are working on a set of query API changes ([sneak peak](https://github.com/googleapis/java-bigquery/pull/1374)). The `cancel` method will be on the `Connection` interface. That should address this problem. It will be coming soon!
