### ISSUE TITLE
BigQuery: review visibilities

### ISSUE THREAD

**Issue by shollyman** [googleapis/java-bigquery#19]
Review visibility in BigQuery classes.  e.g. public methods in classes with default/package private access.

**Comment by shevek** [comment]
Please note that while we appreciate the purism of setting minimal visibility on all things, it makes it absolutely hellish to work around bugs in BigQuery or the Java APIs because if we can't access or extend the necessary helper classes, we have to rewrite the entire world.

**Comment by shevek** [comment]
See also #18 where we had (internally) to replace the entire BigQuery RPC class to work around the issue, rather than  just subclassing it. The issue turnaround on this github, while admirable, is not fast enough that we can afford to block an entire organization waiting for a fix. A careful review of visibilities, marking more things public or protected, or at worst, allowing package-private with a non-sealed JAR file, would make the use of this library much lower risk.

**Comment by stephaniewang526** [comment]
We decided not to change package visibility for now. For workaround, please consider using [discovery-based](https://github.com/gbin/gcloud-java/tree/master/gcloud-java-bigquery) client.
