### ISSUE TITLE
Named parameters do not work with records/subfields

### ISSUE THREAD

**Issue by zlavallee** [googleapis/java-bigquery#207]
Named parameters do not work when executing a query with Record type attributes. The FieldValueList does not pass the schema to the FieldValue and then to the FieldValueList after FieldValue.getRecordValue() is called. This means the schema instance is no longer available and the FieldValueList.get(String name) method no longer works. Also, due to encapsulation, the schema cannot be provided to the FieldValueList once it has been created.

The expected behavior would be passing the schema to the FieldValueList when it is a record type so that named parameters continue to work.

**Comment by stephaniewang526** [comment]
Can you provide us with the code and BigQuery version you're using for us to reproduce the issue?

**Comment by zlavallee** [comment]
Version 1.106.0.

To reproduce, execute a query and get a iterable of FieldValueList.

fieldValueList.get("record_field").getRecordValue().get("field_on_record");

The schema object is not passed on to the nested FieldValueList for the field on the record.

**Comment by stephaniewang526** [comment]
@shollyman PTAL

**Comment by shollyman** [comment]
Seems like named query parameters are a bit of a red herring here (or the reporter is simply refering to named fields of a record's sub-schema).  The issue is all down to nested schema propagation, which we're not doing here correctly.  

e.g. if you get() a record type from fieldvaluelist and schema is present, we should access the corresponding schema field and propagate the nested schema (or fieldlist) when returning the data object.  Unclear without doing more work if we need to consider other accessors/constructors patterns.

**Comment by bartlomiejgraczyk** [comment]
The issue still occurs in com.google.cloud.google-cloud-bigquery:2.38.2.
`fieldValueList.get("repeatedField").getRepeatedValue().get(0).getRecordValue().get("recordValue")`
