### ISSUE TITLE
library update issue when running a jar

### ISSUE THREAD

**Issue by BugsBunnyBR** [googleapis/java-bigquery#2785]
when I change from
```
implementation("com.google.cloud:google-cloud-bigquery:2.19.1")
```

to 
```
implementation("com.google.cloud:google-cloud-bigquery:2.20.1")
```
or newer
and try to run a jar based on that version, I get

```
Error: Could not find or load main class MyPackage.MainKt
Caused by: java.lang.ClassNotFoundException: MyPackagee.MainKt
```

Any ideas of what could it be?

**Comment by Neenu1995** [comment]
Hi @BugsBunnyBR ,
`ClassNotFoundException` normally happens when there is a dependency conflict within your environment. It cannot be debugged with the data provided above. [These](https://github.com/googleapis/java-bigquery/releases/tag/v2.20.0) are the dependency upgrades in the library after v2.19.1 in version 2.20.0. Please make sure other dependencies in your environment are compatible.

**Comment by BugsBunnyBR** [comment]
the problem is that, the missing class is my main class, not in any library.

**Comment by BugsBunnyBR** [comment]
I can't share any code, but I would be happy to do some video call to demonstrate what is happening.

**Comment by Neenu1995** [comment]
Closing this for now. Feel free to reopen.
